# Generated by Django 4.1.5 on 2023-01-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buglist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bugs',
        ),
    ]
