# Generated by Django 4.1.5 on 2023-01-11 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Buglist', '0002_delete_bugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurzbeschreibung', models.CharField(max_length=40, unique=True)),
                ('beschreibung', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=1)),
                ('prio', models.IntegerField()),
                ('melder', models.CharField(max_length=40)),
                ('datum', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('besitzer', models.CharField(max_length=50)),
            ],
        ),
    ]
