# Generated by Django 4.1.5 on 2023-01-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buglist', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='project',
            field=models.ManyToManyField(to='Buglist.projects'),
        ),
    ]
