# Generated by Django 4.1.5 on 2023-01-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buglist', '0004_bugs_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='project',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
