# Generated by Django 4.1.7 on 2023-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buglist', '0007_alter_bugs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='prio',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
